// Code generated by core/rpc/internal/gen from core/iface.go; DO NOT EDIT.

package rpc

import (
	"encoding/json"

	"github.com/aidan-bailey/loom/account"
	"github.com/aidan-bailey/loom/config"
	"github.com/aidan-bailey/loom/core"
	"github.com/aidan-bailey/loom/session"
	"github.com/aidan-bailey/loom/session/github"
	"github.com/aidan-bailey/loom/session/launch"
)

// BeginParams are Begin's parameters on the wire.
type BeginParams struct {
}

// BeginResult is Begin's result on the wire; an error travels in the reply.
type BeginResult struct {
}

// LoadClassicParams are LoadClassic's parameters on the wire.
type LoadClassicParams struct {
	SweepTmux bool `json:"sweepTmux"`
}

// LoadClassicResult is LoadClassic's result on the wire; an error travels in the reply.
type LoadClassicResult struct {
}

// InitAccountsParams are InitAccounts's parameters on the wire.
type InitAccountsParams struct {
}

// InitAccountsResult is InitAccounts's result on the wire; an error travels in the reply.
type InitAccountsResult struct {
}

// SetRCAuthParams are SetRCAuth's parameters on the wire.
type SetRCAuthParams struct {
	Auth session.RemoteControlAuth `json:"auth"`
}

// SetRCAuthResult is SetRCAuth's result on the wire; an error travels in the reply.
type SetRCAuthResult struct {
}

// StayGlobalParams are StayGlobal's parameters on the wire.
type StayGlobalParams struct {
}

// StayGlobalResult is StayGlobal's result on the wire; an error travels in the reply.
type StayGlobalResult struct {
}

// RestoreSavedParams are RestoreSaved's parameters on the wire.
type RestoreSavedParams struct {
	Saved []config.Workspace `json:"saved"`
}

// RestoreSavedResult is RestoreSaved's result on the wire; an error travels in the reply.
type RestoreSavedResult struct {
	Value int `json:"value"`
}

// RestoreFailedParams are RestoreFailed's parameters on the wire.
type RestoreFailedParams struct {
}

// RestoreFailedResult is RestoreFailed's result on the wire; an error travels in the reply.
type RestoreFailedResult struct {
	Value []string `json:"value"`
}

// KeepRestoreFailedParams are KeepRestoreFailed's parameters on the wire.
type KeepRestoreFailedParams struct {
	Desired map[string]bool `json:"desired"`
}

// KeepRestoreFailedResult is KeepRestoreFailed's result on the wire; an error travels in the reply.
type KeepRestoreFailedResult struct {
}

// OpenNamesParams are OpenNames's parameters on the wire.
type OpenNamesParams struct {
}

// OpenNamesResult is OpenNames's result on the wire; an error travels in the reply.
type OpenNamesResult struct {
	Value []string `json:"value"`
}

// PersistOpenListParams are PersistOpenList's parameters on the wire.
type PersistOpenListParams struct {
}

// PersistOpenListResult is PersistOpenList's result on the wire; an error travels in the reply.
type PersistOpenListResult struct {
}

// RegisterParams are Register's parameters on the wire.
type RegisterParams struct {
	Name string `json:"name"`
	Dir  string `json:"dir"`
}

// RegisterResult is Register's result on the wire; an error travels in the reply.
type RegisterResult struct {
	Value config.Workspace `json:"value"`
}

// SetLastUsedParams are SetLastUsed's parameters on the wire.
type SetLastUsedParams struct {
	Name string `json:"name"`
}

// SetLastUsedResult is SetLastUsed's result on the wire; an error travels in the reply.
type SetLastUsedResult struct {
}

// SaveForQuitParams are SaveForQuit's parameters on the wire.
type SaveForQuitParams struct {
}

// SaveForQuitResult is SaveForQuit's result on the wire; an error travels in the reply.
type SaveForQuitResult struct {
}

// WorkspaceParams are Workspace's parameters on the wire.
type WorkspaceParams struct {
	ID core.WorkspaceID `json:"id"`
}

// WorkspaceResult is Workspace's result on the wire; an error travels in the reply.
type WorkspaceResult struct {
	Value core.WorkspaceView `json:"value"`
	OK    bool               `json:"ok"`
}

// ClassicParams are Classic's parameters on the wire.
type ClassicParams struct {
}

// ClassicResult is Classic's result on the wire; an error travels in the reply.
type ClassicResult struct {
	Value core.WorkspaceView `json:"value"`
	OK    bool               `json:"ok"`
}

// TabsParams are Tabs's parameters on the wire.
type TabsParams struct {
}

// TabsResult is Tabs's result on the wire; an error travels in the reply.
type TabsResult struct {
	Value []core.WorkspaceView `json:"value"`
}

// IsLoadedParams are IsLoaded's parameters on the wire.
type IsLoadedParams struct {
	ID core.WorkspaceID `json:"id"`
}

// IsLoadedResult is IsLoaded's result on the wire; an error travels in the reply.
type IsLoadedResult struct {
	Value bool `json:"value"`
}

// OpenTabParams are OpenTab's parameters on the wire.
type OpenTabParams struct {
	Workspace config.Workspace `json:"workspace"`
}

// OpenTabResult is OpenTab's result on the wire; an error travels in the reply.
type OpenTabResult struct {
	Value core.WorkspaceView `json:"value"`
}

// CloseTabParams are CloseTab's parameters on the wire.
type CloseTabParams struct {
	Name string `json:"name"`
}

// CloseTabResult is CloseTab's result on the wire; an error travels in the reply.
type CloseTabResult struct {
}

// EnterGlobalParams are EnterGlobal's parameters on the wire.
type EnterGlobalParams struct {
	Focused core.WorkspaceID `json:"focused"`
}

// EnterGlobalResult is EnterGlobal's result on the wire; an error travels in the reply.
type EnterGlobalResult struct {
	Value core.WorkspaceView `json:"value"`
}

// SaveParams are Save's parameters on the wire.
type SaveParams struct {
	ID core.WorkspaceID `json:"id"`
}

// SaveResult is Save's result on the wire; an error travels in the reply.
type SaveResult struct {
}

// RegistryParams are Registry's parameters on the wire.
type RegistryParams struct {
}

// RegistryResult is Registry's result on the wire; an error travels in the reply.
type RegistryResult struct {
	Value core.RegistryView `json:"value"`
}

// ReloadRegistryParams are ReloadRegistry's parameters on the wire.
type ReloadRegistryParams struct {
}

// ReloadRegistryResult is ReloadRegistry's result on the wire; an error travels in the reply.
type ReloadRegistryResult struct {
}

// SaveSettingsParams are SaveSettings's parameters on the wire.
type SaveSettingsParams struct {
	ID       core.WorkspaceID `json:"id"`
	Settings config.Settings  `json:"settings"`
}

// SaveSettingsResult is SaveSettings's result on the wire; an error travels in the reply.
type SaveSettingsResult struct {
}

// SetUIPrefsParams are SetUIPrefs's parameters on the wire.
type SetUIPrefsParams struct {
	ID    core.WorkspaceID `json:"id"`
	Prefs config.UIPrefs   `json:"prefs"`
}

// SetUIPrefsResult is SetUIPrefs's result on the wire; an error travels in the reply.
type SetUIPrefsResult struct {
}

// SetHelpScreensSeenParams are SetHelpScreensSeen's parameters on the wire.
type SetHelpScreensSeenParams struct {
	ID   core.WorkspaceID `json:"id"`
	Seen uint32           `json:"seen"`
}

// SetHelpScreensSeenResult is SetHelpScreensSeen's result on the wire; an error travels in the reply.
type SetHelpScreensSeenResult struct {
}

// ViewsParams are Views's parameters on the wire.
type ViewsParams struct {
	ID core.WorkspaceID `json:"id"`
}

// ViewsResult is Views's result on the wire; an error travels in the reply.
type ViewsResult struct {
	Value []core.InstanceView `json:"value"`
}

// ViewParams are View's parameters on the wire.
type ViewParams struct {
	ID core.InstanceID `json:"id"`
}

// ViewResult is View's result on the wire; an error travels in the reply.
type ViewResult struct {
	Value core.InstanceView `json:"value"`
	OK    bool              `json:"ok"`
}

// CreateParams are Create's parameters on the wire.
type CreateParams struct {
	ID   core.WorkspaceID `json:"id"`
	Spec core.NewInstance `json:"spec"`
	Req  core.ReqID       `json:"req"`
}

// CreateResult is Create's result on the wire; an error travels in the reply.
type CreateResult struct {
}

// KillParams are Kill's parameters on the wire.
type KillParams struct {
	ID  core.InstanceID `json:"id"`
	Req core.ReqID      `json:"req"`
}

// KillResult is Kill's result on the wire; an error travels in the reply.
type KillResult struct {
}

// PauseParams are Pause's parameters on the wire.
type PauseParams struct {
	ID  core.InstanceID `json:"id"`
	Req core.ReqID      `json:"req"`
}

// PauseResult is Pause's result on the wire; an error travels in the reply.
type PauseResult struct {
}

// ResumeParams are Resume's parameters on the wire.
type ResumeParams struct {
	ID  core.InstanceID `json:"id"`
	Req core.ReqID      `json:"req"`
}

// ResumeResult is Resume's result on the wire; an error travels in the reply.
type ResumeResult struct {
}

// ResumeWithParams are ResumeWith's parameters on the wire.
type ResumeWithParams struct {
	ID   core.InstanceID `json:"id"`
	Opts launch.Options  `json:"opts"`
	Base string          `json:"base"`
	Req  core.ReqID      `json:"req"`
}

// ResumeWithResult is ResumeWith's result on the wire; an error travels in the reply.
type ResumeWithResult struct {
}

// RecoverParams are Recover's parameters on the wire.
type RecoverParams struct {
	ID  core.InstanceID `json:"id"`
	Req core.ReqID      `json:"req"`
}

// RecoverResult is Recover's result on the wire; an error travels in the reply.
type RecoverResult struct {
}

// MergeParams are Merge's parameters on the wire.
type MergeParams struct {
	Target core.InstanceID `json:"target"`
	Source core.InstanceID `json:"source"`
	Req    core.ReqID      `json:"req"`
}

// MergeResult is Merge's result on the wire; an error travels in the reply.
type MergeResult struct {
}

// PushParams are Push's parameters on the wire.
type PushParams struct {
	ID  core.InstanceID `json:"id"`
	Req core.ReqID      `json:"req"`
}

// PushResult is Push's result on the wire; an error travels in the reply.
type PushResult struct {
}

// SendPromptParams are SendPrompt's parameters on the wire.
type SendPromptParams struct {
	ID   core.InstanceID `json:"id"`
	Text string          `json:"text"`
	Req  core.ReqID      `json:"req"`
}

// SendPromptResult is SendPrompt's result on the wire; an error travels in the reply.
type SendPromptResult struct {
}

// FetchIssueParams are FetchIssue's parameters on the wire.
type FetchIssueParams struct {
	Repo   string     `json:"repo"`
	Number int        `json:"number"`
	Req    core.ReqID `json:"req"`
}

// FetchIssueResult is FetchIssue's result on the wire; an error travels in the reply.
type FetchIssueResult struct {
}

// SetSelectedParams are SetSelected's parameters on the wire.
type SetSelectedParams struct {
	ID core.InstanceID `json:"id"`
}

// SetSelectedResult is SetSelected's result on the wire; an error travels in the reply.
type SetSelectedResult struct {
}

// MarkOutputParams are MarkOutput's parameters on the wire.
type MarkOutputParams struct {
	SessionName string `json:"sessionName"`
}

// MarkOutputResult is MarkOutput's result on the wire; an error travels in the reply.
type MarkOutputResult struct {
}

// PaneOutputParams are PaneOutput's parameters on the wire.
type PaneOutputParams struct {
	ID core.InstanceID `json:"id"`
}

// PaneOutputResult is PaneOutput's result on the wire; an error travels in the reply.
type PaneOutputResult struct {
}

// PaneQuietParams are PaneQuiet's parameters on the wire.
type PaneQuietParams struct {
	ID core.InstanceID `json:"id"`
}

// PaneQuietResult is PaneQuiet's result on the wire; an error travels in the reply.
type PaneQuietResult struct {
}

// VerifyDeadParams are VerifyDead's parameters on the wire.
type VerifyDeadParams struct {
	ID core.InstanceID `json:"id"`
}

// VerifyDeadResult is VerifyDead's result on the wire; an error travels in the reply.
type VerifyDeadResult struct {
}

// ProgramParams are Program's parameters on the wire.
type ProgramParams struct {
}

// ProgramResult is Program's result on the wire; an error travels in the reply.
type ProgramResult struct {
	Value string `json:"value"`
}

// SetProgramParams are SetProgram's parameters on the wire.
type SetProgramParams struct {
	Program string `json:"program"`
}

// SetProgramResult is SetProgram's result on the wire; an error travels in the reply.
type SetProgramResult struct {
}

// RCAuthParams are RCAuth's parameters on the wire.
type RCAuthParams struct {
}

// RCAuthResult is RCAuth's result on the wire; an error travels in the reply.
type RCAuthResult struct {
	Value session.RemoteControlAuth `json:"value"`
}

// GitHubSnapshotParams are GitHubSnapshot's parameters on the wire.
type GitHubSnapshotParams struct {
	Repo string `json:"repo"`
}

// GitHubSnapshotResult is GitHubSnapshot's result on the wire; an error travels in the reply.
type GitHubSnapshotResult struct {
	Value github.Snapshot `json:"value"`
	OK    bool            `json:"ok"`
}

// GitHubErrParams are GitHubErr's parameters on the wire.
type GitHubErrParams struct {
	Repo string `json:"repo"`
}

// GitHubErrResult is GitHubErr's result on the wire; an error travels in the reply.
type GitHubErrResult struct {
}

// GitHubUnavailableParams are GitHubUnavailable's parameters on the wire.
type GitHubUnavailableParams struct {
}

// GitHubUnavailableResult is GitHubUnavailable's result on the wire; an error travels in the reply.
type GitHubUnavailableResult struct {
	Value bool `json:"value"`
}

// GitHubUnavailableReasonParams are GitHubUnavailableReason's parameters on the wire.
type GitHubUnavailableReasonParams struct {
}

// GitHubUnavailableReasonResult is GitHubUnavailableReason's result on the wire; an error travels in the reply.
type GitHubUnavailableReasonResult struct {
	Value string `json:"value"`
}

// ExpediteGitHubParams are ExpediteGitHub's parameters on the wire.
type ExpediteGitHubParams struct {
}

// ExpediteGitHubResult is ExpediteGitHub's result on the wire; an error travels in the reply.
type ExpediteGitHubResult struct {
}

// AccountNamesParams are AccountNames's parameters on the wire.
type AccountNamesParams struct {
}

// AccountNamesResult is AccountNames's result on the wire; an error travels in the reply.
type AccountNamesResult struct {
	Value core.AccountNames `json:"value"`
}

// AccountsLoadedParams are AccountsLoaded's parameters on the wire.
type AccountsLoadedParams struct {
}

// AccountsLoadedResult is AccountsLoaded's result on the wire; an error travels in the reply.
type AccountsLoadedResult struct {
	Value bool `json:"value"`
}

// HasExtraAccountsParams are HasExtraAccounts's parameters on the wire.
type HasExtraAccountsParams struct {
}

// HasExtraAccountsResult is HasExtraAccounts's result on the wire; an error travels in the reply.
type HasExtraAccountsResult struct {
	Value bool `json:"value"`
}

// AccountParams are Account's parameters on the wire.
type AccountParams struct {
	Name string `json:"name"`
}

// AccountResult is Account's result on the wire; an error travels in the reply.
type AccountResult struct {
	Value account.Account `json:"value"`
	OK    bool            `json:"ok"`
}

// RCAuthForParams are RCAuthFor's parameters on the wire.
type RCAuthForParams struct {
	Acct string `json:"acct"`
}

// RCAuthForResult is RCAuthFor's result on the wire; an error travels in the reply.
type RCAuthForResult struct {
	Value session.RemoteControlAuth `json:"value"`
}

// AccountLoggedOutParams are AccountLoggedOut's parameters on the wire.
type AccountLoggedOutParams struct {
	Acct string `json:"acct"`
}

// AccountLoggedOutResult is AccountLoggedOut's result on the wire; an error travels in the reply.
type AccountLoggedOutResult struct {
	Value bool `json:"value"`
}

// AccountSyncParams are AccountSync's parameters on the wire.
type AccountSyncParams struct {
	Name string `json:"name"`
}

// AccountSyncResult is AccountSync's result on the wire; an error travels in the reply.
type AccountSyncResult struct {
	Value account.SyncReport `json:"value"`
	OK    bool               `json:"ok"`
}

// AccountUsageParams are AccountUsage's parameters on the wire.
type AccountUsageParams struct {
	Name string `json:"name"`
}

// AccountUsageResult is AccountUsage's result on the wire; an error travels in the reply.
type AccountUsageResult struct {
	Value account.Usage `json:"value"`
}

// AccountEnvParams are AccountEnv's parameters on the wire.
type AccountEnvParams struct {
	Name string `json:"name"`
}

// AccountEnvResult is AccountEnv's result on the wire; an error travels in the reply.
type AccountEnvResult struct {
	Value []string `json:"value"`
}

// ClaudeProgramParams are ClaudeProgram's parameters on the wire.
type ClaudeProgramParams struct {
}

// ClaudeProgramResult is ClaudeProgram's result on the wire; an error travels in the reply.
type ClaudeProgramResult struct {
	Value string `json:"value"`
}

// ReloadAccountsParams are ReloadAccounts's parameters on the wire.
type ReloadAccountsParams struct {
}

// ReloadAccountsResult is ReloadAccounts's result on the wire; an error travels in the reply.
type ReloadAccountsResult struct {
}

// RequestAccountsRefreshParams are RequestAccountsRefresh's parameters on the wire.
type RequestAccountsRefreshParams struct {
	WithDefault bool `json:"withDefault"`
}

// RequestAccountsRefreshResult is RequestAccountsRefresh's result on the wire; an error travels in the reply.
type RequestAccountsRefreshResult struct {
}

// RequestUsageProbeParams are RequestUsageProbe's parameters on the wire.
type RequestUsageProbeParams struct {
}

// RequestUsageProbeResult is RequestUsageProbe's result on the wire; an error travels in the reply.
type RequestUsageProbeResult struct {
}

// AddAccountParams are AddAccount's parameters on the wire.
type AddAccountParams struct {
	Name string `json:"name"`
}

// AddAccountResult is AddAccount's result on the wire; an error travels in the reply.
type AddAccountResult struct {
	Value string `json:"value"`
}

// RemoveAccountParams are RemoveAccount's parameters on the wire.
type RemoveAccountParams struct {
	Name string `json:"name"`
}

// RemoveAccountResult is RemoveAccount's result on the wire; an error travels in the reply.
type RemoveAccountResult struct {
}

// SetDefaultAccountParams are SetDefaultAccount's parameters on the wire.
type SetDefaultAccountParams struct {
	Name string `json:"name"`
}

// SetDefaultAccountResult is SetDefaultAccount's result on the wire; an error travels in the reply.
type SetDefaultAccountResult struct {
}

// methods are the Core methods the wire carries, in iface.go's order, with
// how a client serves each (its line comment there).
var methods = []methodInfo{
	{Name: "Begin", Kind: kindRequest, Params: BeginParams{}, Result: BeginResult{}},
	{Name: "LoadClassic", Kind: kindRequest, Params: LoadClassicParams{}, Result: LoadClassicResult{}},
	{Name: "InitAccounts", Kind: kindRequest, Params: InitAccountsParams{}, Result: InitAccountsResult{}},
	{Name: "SetRCAuth", Kind: kindRequest, Params: SetRCAuthParams{}, Result: SetRCAuthResult{}},
	{Name: "StayGlobal", Kind: kindRequest, Params: StayGlobalParams{}, Result: StayGlobalResult{}},
	{Name: "RestoreSaved", Kind: kindRequest, Params: RestoreSavedParams{}, Result: RestoreSavedResult{}},
	{Name: "RestoreFailed", Kind: kindLocal, Params: RestoreFailedParams{}, Result: RestoreFailedResult{}},
	{Name: "KeepRestoreFailed", Kind: kindRequest, Params: KeepRestoreFailedParams{}, Result: KeepRestoreFailedResult{}},
	{Name: "OpenNames", Kind: kindLocal, Params: OpenNamesParams{}, Result: OpenNamesResult{}},
	{Name: "PersistOpenList", Kind: kindRequest, Params: PersistOpenListParams{}, Result: PersistOpenListResult{}},
	{Name: "Register", Kind: kindRequest, Params: RegisterParams{}, Result: RegisterResult{}},
	{Name: "SetLastUsed", Kind: kindRequest, Params: SetLastUsedParams{}, Result: SetLastUsedResult{}},
	{Name: "SaveForQuit", Kind: kindRequest, Params: SaveForQuitParams{}, Result: SaveForQuitResult{}},
	{Name: "Workspace", Kind: kindLocal, Params: WorkspaceParams{}, Result: WorkspaceResult{}},
	{Name: "Classic", Kind: kindLocal, Params: ClassicParams{}, Result: ClassicResult{}},
	{Name: "Tabs", Kind: kindLocal, Params: TabsParams{}, Result: TabsResult{}},
	{Name: "IsLoaded", Kind: kindLocal, Params: IsLoadedParams{}, Result: IsLoadedResult{}},
	{Name: "OpenTab", Kind: kindRequest, Params: OpenTabParams{}, Result: OpenTabResult{}},
	{Name: "CloseTab", Kind: kindRequest, Params: CloseTabParams{}, Result: CloseTabResult{}},
	{Name: "EnterGlobal", Kind: kindRequest, Params: EnterGlobalParams{}, Result: EnterGlobalResult{}},
	{Name: "Save", Kind: kindRequest, Params: SaveParams{}, Result: SaveResult{}},
	{Name: "Registry", Kind: kindLocal, Params: RegistryParams{}, Result: RegistryResult{}},
	{Name: "ReloadRegistry", Kind: kindRequest, Params: ReloadRegistryParams{}, Result: ReloadRegistryResult{}},
	{Name: "SaveSettings", Kind: kindRequest, Params: SaveSettingsParams{}, Result: SaveSettingsResult{}},
	{Name: "SetUIPrefs", Kind: kindRequest, Params: SetUIPrefsParams{}, Result: SetUIPrefsResult{}},
	{Name: "SetHelpScreensSeen", Kind: kindRequest, Params: SetHelpScreensSeenParams{}, Result: SetHelpScreensSeenResult{}},
	{Name: "Views", Kind: kindLocal, Params: ViewsParams{}, Result: ViewsResult{}},
	{Name: "View", Kind: kindLocal, Params: ViewParams{}, Result: ViewResult{}},
	{Name: "Create", Kind: kindRequest, Params: CreateParams{}, Result: CreateResult{}},
	{Name: "Kill", Kind: kindRequest, Params: KillParams{}, Result: KillResult{}},
	{Name: "Pause", Kind: kindRequest, Params: PauseParams{}, Result: PauseResult{}},
	{Name: "Resume", Kind: kindRequest, Params: ResumeParams{}, Result: ResumeResult{}},
	{Name: "ResumeWith", Kind: kindRequest, Params: ResumeWithParams{}, Result: ResumeWithResult{}},
	{Name: "Recover", Kind: kindRequest, Params: RecoverParams{}, Result: RecoverResult{}},
	{Name: "Merge", Kind: kindRequest, Params: MergeParams{}, Result: MergeResult{}},
	{Name: "Push", Kind: kindRequest, Params: PushParams{}, Result: PushResult{}},
	{Name: "SendPrompt", Kind: kindRequest, Params: SendPromptParams{}, Result: SendPromptResult{}},
	{Name: "FetchIssue", Kind: kindRequest, Params: FetchIssueParams{}, Result: FetchIssueResult{}},
	{Name: "SetSelected", Kind: kindCast, Params: SetSelectedParams{}, Result: SetSelectedResult{}},
	{Name: "MarkOutput", Kind: kindCast, Params: MarkOutputParams{}, Result: MarkOutputResult{}},
	{Name: "PaneOutput", Kind: kindCast, Params: PaneOutputParams{}, Result: PaneOutputResult{}},
	{Name: "PaneQuiet", Kind: kindCast, Params: PaneQuietParams{}, Result: PaneQuietResult{}},
	{Name: "VerifyDead", Kind: kindCast, Params: VerifyDeadParams{}, Result: VerifyDeadResult{}},
	{Name: "Program", Kind: kindLocal, Params: ProgramParams{}, Result: ProgramResult{}},
	{Name: "SetProgram", Kind: kindRequest, Params: SetProgramParams{}, Result: SetProgramResult{}},
	{Name: "RCAuth", Kind: kindLocal, Params: RCAuthParams{}, Result: RCAuthResult{}},
	{Name: "GitHubSnapshot", Kind: kindLocal, Params: GitHubSnapshotParams{}, Result: GitHubSnapshotResult{}},
	{Name: "GitHubErr", Kind: kindLocal, Params: GitHubErrParams{}, Result: GitHubErrResult{}},
	{Name: "GitHubUnavailable", Kind: kindLocal, Params: GitHubUnavailableParams{}, Result: GitHubUnavailableResult{}},
	{Name: "GitHubUnavailableReason", Kind: kindLocal, Params: GitHubUnavailableReasonParams{}, Result: GitHubUnavailableReasonResult{}},
	{Name: "ExpediteGitHub", Kind: kindCast, Params: ExpediteGitHubParams{}, Result: ExpediteGitHubResult{}},
	{Name: "AccountNames", Kind: kindLocal, Params: AccountNamesParams{}, Result: AccountNamesResult{}},
	{Name: "AccountsLoaded", Kind: kindLocal, Params: AccountsLoadedParams{}, Result: AccountsLoadedResult{}},
	{Name: "HasExtraAccounts", Kind: kindLocal, Params: HasExtraAccountsParams{}, Result: HasExtraAccountsResult{}},
	{Name: "Account", Kind: kindLocal, Params: AccountParams{}, Result: AccountResult{}},
	{Name: "RCAuthFor", Kind: kindLocal, Params: RCAuthForParams{}, Result: RCAuthForResult{}},
	{Name: "AccountLoggedOut", Kind: kindLocal, Params: AccountLoggedOutParams{}, Result: AccountLoggedOutResult{}},
	{Name: "AccountSync", Kind: kindLocal, Params: AccountSyncParams{}, Result: AccountSyncResult{}},
	{Name: "AccountUsage", Kind: kindLocal, Params: AccountUsageParams{}, Result: AccountUsageResult{}},
	{Name: "AccountEnv", Kind: kindLocal, Params: AccountEnvParams{}, Result: AccountEnvResult{}},
	{Name: "ClaudeProgram", Kind: kindLocal, Params: ClaudeProgramParams{}, Result: ClaudeProgramResult{}},
	{Name: "ReloadAccounts", Kind: kindRequest, Params: ReloadAccountsParams{}, Result: ReloadAccountsResult{}},
	{Name: "RequestAccountsRefresh", Kind: kindCast, Params: RequestAccountsRefreshParams{}, Result: RequestAccountsRefreshResult{}},
	{Name: "RequestUsageProbe", Kind: kindCast, Params: RequestUsageProbeParams{}, Result: RequestUsageProbeResult{}},
	{Name: "AddAccount", Kind: kindRequest, Params: AddAccountParams{}, Result: AddAccountResult{}},
	{Name: "RemoveAccount", Kind: kindRequest, Params: RemoveAccountParams{}, Result: RemoveAccountResult{}},
	{Name: "SetDefaultAccount", Kind: kindRequest, Params: SetDefaultAccountParams{}, Result: SetDefaultAccountResult{}},
}

// dispatch calls method on b with params decoded, returning its result
// for the reply and its error; found is false for a method the wire does
// not carry. tag rewrites every request ID (core.ReqID) the params carry
// into the server's, which names the connection (see Server).
func dispatch(b core.Core, method string, params json.RawMessage, tag func(*core.ReqID) error) (result any, err error, found bool) {
	switch method {
	case "Begin":
		var p BeginParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.Begin()
		return BeginResult{}, nil, true
	case "LoadClassic":
		var p LoadClassicParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.LoadClassic(p.SweepTmux)
		return LoadClassicResult{}, err, true
	case "InitAccounts":
		var p InitAccountsParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.InitAccounts()
		return InitAccountsResult{}, nil, true
	case "SetRCAuth":
		var p SetRCAuthParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.SetRCAuth(p.Auth)
		return SetRCAuthResult{}, nil, true
	case "StayGlobal":
		var p StayGlobalParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.StayGlobal()
		return StayGlobalResult{}, nil, true
	case "RestoreSaved":
		var p RestoreSavedParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return RestoreSavedResult{Value: b.RestoreSaved(p.Saved)}, nil, true
	case "RestoreFailed":
		var p RestoreFailedParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return RestoreFailedResult{Value: b.RestoreFailed()}, nil, true
	case "KeepRestoreFailed":
		var p KeepRestoreFailedParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.KeepRestoreFailed(p.Desired)
		return KeepRestoreFailedResult{}, nil, true
	case "OpenNames":
		var p OpenNamesParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return OpenNamesResult{Value: b.OpenNames()}, nil, true
	case "PersistOpenList":
		var p PersistOpenListParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.PersistOpenList()
		return PersistOpenListResult{}, nil, true
	case "Register":
		var p RegisterParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, err := b.Register(p.Name, p.Dir)
		return RegisterResult{Value: v}, err, true
	case "SetLastUsed":
		var p SetLastUsedParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.SetLastUsed(p.Name)
		return SetLastUsedResult{}, err, true
	case "SaveForQuit":
		var p SaveForQuitParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.SaveForQuit()
		return SaveForQuitResult{}, err, true
	case "Workspace":
		var p WorkspaceParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, ok := b.Workspace(p.ID)
		return WorkspaceResult{Value: v, OK: ok}, nil, true
	case "Classic":
		var p ClassicParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, ok := b.Classic()
		return ClassicResult{Value: v, OK: ok}, nil, true
	case "Tabs":
		var p TabsParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return TabsResult{Value: b.Tabs()}, nil, true
	case "IsLoaded":
		var p IsLoadedParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return IsLoadedResult{Value: b.IsLoaded(p.ID)}, nil, true
	case "OpenTab":
		var p OpenTabParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, err := b.OpenTab(p.Workspace)
		return OpenTabResult{Value: v}, err, true
	case "CloseTab":
		var p CloseTabParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.CloseTab(p.Name)
		return CloseTabResult{}, err, true
	case "EnterGlobal":
		var p EnterGlobalParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, err := b.EnterGlobal(p.Focused)
		return EnterGlobalResult{Value: v}, err, true
	case "Save":
		var p SaveParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.Save(p.ID)
		return SaveResult{}, err, true
	case "Registry":
		var p RegistryParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return RegistryResult{Value: b.Registry()}, nil, true
	case "ReloadRegistry":
		var p ReloadRegistryParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.ReloadRegistry()
		return ReloadRegistryResult{}, err, true
	case "SaveSettings":
		var p SaveSettingsParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.SaveSettings(p.ID, p.Settings)
		return SaveSettingsResult{}, err, true
	case "SetUIPrefs":
		var p SetUIPrefsParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.SetUIPrefs(p.ID, p.Prefs)
		return SetUIPrefsResult{}, err, true
	case "SetHelpScreensSeen":
		var p SetHelpScreensSeenParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.SetHelpScreensSeen(p.ID, p.Seen)
		return SetHelpScreensSeenResult{}, err, true
	case "Views":
		var p ViewsParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return ViewsResult{Value: b.Views(p.ID)}, nil, true
	case "View":
		var p ViewParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, ok := b.View(p.ID)
		return ViewResult{Value: v, OK: ok}, nil, true
	case "Create":
		var p CreateParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.Create(p.ID, p.Spec, p.Req)
		return CreateResult{}, nil, true
	case "Kill":
		var p KillParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.Kill(p.ID, p.Req)
		return KillResult{}, nil, true
	case "Pause":
		var p PauseParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.Pause(p.ID, p.Req)
		return PauseResult{}, nil, true
	case "Resume":
		var p ResumeParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.Resume(p.ID, p.Req)
		return ResumeResult{}, nil, true
	case "ResumeWith":
		var p ResumeWithParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.ResumeWith(p.ID, p.Opts, p.Base, p.Req)
		return ResumeWithResult{}, nil, true
	case "Recover":
		var p RecoverParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.Recover(p.ID, p.Req)
		return RecoverResult{}, nil, true
	case "Merge":
		var p MergeParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.Merge(p.Target, p.Source, p.Req)
		return MergeResult{}, nil, true
	case "Push":
		var p PushParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.Push(p.ID, p.Req)
		return PushResult{}, nil, true
	case "SendPrompt":
		var p SendPromptParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.SendPrompt(p.ID, p.Text, p.Req)
		return SendPromptResult{}, nil, true
	case "FetchIssue":
		var p FetchIssueParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		if err := tag(&p.Req); err != nil {
			return nil, err, true
		}
		b.FetchIssue(p.Repo, p.Number, p.Req)
		return FetchIssueResult{}, nil, true
	case "SetSelected":
		var p SetSelectedParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.SetSelected(p.ID)
		return SetSelectedResult{}, nil, true
	case "MarkOutput":
		var p MarkOutputParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.MarkOutput(p.SessionName)
		return MarkOutputResult{}, nil, true
	case "PaneOutput":
		var p PaneOutputParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.PaneOutput(p.ID)
		return PaneOutputResult{}, nil, true
	case "PaneQuiet":
		var p PaneQuietParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.PaneQuiet(p.ID)
		return PaneQuietResult{}, nil, true
	case "VerifyDead":
		var p VerifyDeadParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.VerifyDead(p.ID)
		return VerifyDeadResult{}, nil, true
	case "Program":
		var p ProgramParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return ProgramResult{Value: b.Program()}, nil, true
	case "SetProgram":
		var p SetProgramParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.SetProgram(p.Program)
		return SetProgramResult{}, nil, true
	case "RCAuth":
		var p RCAuthParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return RCAuthResult{Value: b.RCAuth()}, nil, true
	case "GitHubSnapshot":
		var p GitHubSnapshotParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, ok := b.GitHubSnapshot(p.Repo)
		return GitHubSnapshotResult{Value: v, OK: ok}, nil, true
	case "GitHubErr":
		var p GitHubErrParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.GitHubErr(p.Repo)
		return GitHubErrResult{}, err, true
	case "GitHubUnavailable":
		var p GitHubUnavailableParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return GitHubUnavailableResult{Value: b.GitHubUnavailable()}, nil, true
	case "GitHubUnavailableReason":
		var p GitHubUnavailableReasonParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return GitHubUnavailableReasonResult{Value: b.GitHubUnavailableReason()}, nil, true
	case "ExpediteGitHub":
		var p ExpediteGitHubParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.ExpediteGitHub()
		return ExpediteGitHubResult{}, nil, true
	case "AccountNames":
		var p AccountNamesParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return AccountNamesResult{Value: b.AccountNames()}, nil, true
	case "AccountsLoaded":
		var p AccountsLoadedParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return AccountsLoadedResult{Value: b.AccountsLoaded()}, nil, true
	case "HasExtraAccounts":
		var p HasExtraAccountsParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return HasExtraAccountsResult{Value: b.HasExtraAccounts()}, nil, true
	case "Account":
		var p AccountParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, ok := b.Account(p.Name)
		return AccountResult{Value: v, OK: ok}, nil, true
	case "RCAuthFor":
		var p RCAuthForParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return RCAuthForResult{Value: b.RCAuthFor(p.Acct)}, nil, true
	case "AccountLoggedOut":
		var p AccountLoggedOutParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return AccountLoggedOutResult{Value: b.AccountLoggedOut(p.Acct)}, nil, true
	case "AccountSync":
		var p AccountSyncParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, ok := b.AccountSync(p.Name)
		return AccountSyncResult{Value: v, OK: ok}, nil, true
	case "AccountUsage":
		var p AccountUsageParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, err := b.AccountUsage(p.Name)
		return AccountUsageResult{Value: v}, err, true
	case "AccountEnv":
		var p AccountEnvParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, err := b.AccountEnv(p.Name)
		return AccountEnvResult{Value: v}, err, true
	case "ClaudeProgram":
		var p ClaudeProgramParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		return ClaudeProgramResult{Value: b.ClaudeProgram()}, nil, true
	case "ReloadAccounts":
		var p ReloadAccountsParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.ReloadAccounts()
		return ReloadAccountsResult{}, nil, true
	case "RequestAccountsRefresh":
		var p RequestAccountsRefreshParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.RequestAccountsRefresh(p.WithDefault)
		return RequestAccountsRefreshResult{}, nil, true
	case "RequestUsageProbe":
		var p RequestUsageProbeParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		b.RequestUsageProbe()
		return RequestUsageProbeResult{}, nil, true
	case "AddAccount":
		var p AddAccountParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		v, err := b.AddAccount(p.Name)
		return AddAccountResult{Value: v}, err, true
	case "RemoveAccount":
		var p RemoveAccountParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.RemoveAccount(p.Name)
		return RemoveAccountResult{}, err, true
	case "SetDefaultAccount":
		var p SetDefaultAccountParams
		if err := decodeParams(params, &p); err != nil {
			return nil, err, true
		}
		err := b.SetDefaultAccount(p.Name)
		return SetDefaultAccountResult{}, err, true
	}
	return nil, nil, false
}

// Begin is core.Core's Begin (request).
func (c *Client) Begin() {
	var r BeginResult
	c.requestNoErr("Begin", BeginParams{}, &r)
}

// LoadClassic is core.Core's LoadClassic (request).
func (c *Client) LoadClassic(sweepTmux bool) error {
	var r LoadClassicResult
	return c.request("LoadClassic", LoadClassicParams{SweepTmux: sweepTmux}, &r)
}

// InitAccounts is core.Core's InitAccounts (request).
func (c *Client) InitAccounts() {
	var r InitAccountsResult
	c.requestNoErr("InitAccounts", InitAccountsParams{}, &r)
}

// SetRCAuth is core.Core's SetRCAuth (request).
func (c *Client) SetRCAuth(auth session.RemoteControlAuth) {
	var r SetRCAuthResult
	c.requestNoErr("SetRCAuth", SetRCAuthParams{Auth: auth}, &r)
}

// StayGlobal is core.Core's StayGlobal (request).
func (c *Client) StayGlobal() {
	var r StayGlobalResult
	c.requestNoErr("StayGlobal", StayGlobalParams{}, &r)
}

// RestoreSaved is core.Core's RestoreSaved (request).
func (c *Client) RestoreSaved(saved []config.Workspace) int {
	var r RestoreSavedResult
	c.requestNoErr("RestoreSaved", RestoreSavedParams{Saved: saved}, &r)
	return r.Value
}

// RestoreFailed is core.Core's RestoreFailed (local).
func (c *Client) RestoreFailed() []string {
	var v0 []string
	c.local(func(r *replica) { v0 = r.RestoreFailed() })
	return v0
}

// KeepRestoreFailed is core.Core's KeepRestoreFailed (request).
func (c *Client) KeepRestoreFailed(desired map[string]bool) {
	var r KeepRestoreFailedResult
	c.requestNoErr("KeepRestoreFailed", KeepRestoreFailedParams{Desired: desired}, &r)
}

// OpenNames is core.Core's OpenNames (local).
func (c *Client) OpenNames() []string {
	var v0 []string
	c.local(func(r *replica) { v0 = r.OpenNames() })
	return v0
}

// PersistOpenList is core.Core's PersistOpenList (request).
func (c *Client) PersistOpenList() {
	var r PersistOpenListResult
	c.requestNoErr("PersistOpenList", PersistOpenListParams{}, &r)
}

// Register is core.Core's Register (request).
func (c *Client) Register(name string, dir string) (config.Workspace, error) {
	var r RegisterResult
	err := c.request("Register", RegisterParams{Name: name, Dir: dir}, &r)
	return r.Value, err
}

// SetLastUsed is core.Core's SetLastUsed (request).
func (c *Client) SetLastUsed(name string) error {
	var r SetLastUsedResult
	return c.request("SetLastUsed", SetLastUsedParams{Name: name}, &r)
}

// SaveForQuit is core.Core's SaveForQuit (request).
func (c *Client) SaveForQuit() error {
	var r SaveForQuitResult
	return c.request("SaveForQuit", SaveForQuitParams{}, &r)
}

// Workspace is core.Core's Workspace (local).
func (c *Client) Workspace(id core.WorkspaceID) (core.WorkspaceView, bool) {
	var v0 core.WorkspaceView
	var v1 bool
	c.local(func(r *replica) { v0, v1 = r.Workspace(id) })
	return v0, v1
}

// Classic is core.Core's Classic (local).
func (c *Client) Classic() (core.WorkspaceView, bool) {
	var v0 core.WorkspaceView
	var v1 bool
	c.local(func(r *replica) { v0, v1 = r.Classic() })
	return v0, v1
}

// Tabs is core.Core's Tabs (local).
func (c *Client) Tabs() []core.WorkspaceView {
	var v0 []core.WorkspaceView
	c.local(func(r *replica) { v0 = r.Tabs() })
	return v0
}

// IsLoaded is core.Core's IsLoaded (local).
func (c *Client) IsLoaded(id core.WorkspaceID) bool {
	var v0 bool
	c.local(func(r *replica) { v0 = r.IsLoaded(id) })
	return v0
}

// OpenTab is core.Core's OpenTab (request).
func (c *Client) OpenTab(workspace config.Workspace) (core.WorkspaceView, error) {
	var r OpenTabResult
	err := c.request("OpenTab", OpenTabParams{Workspace: workspace}, &r)
	return r.Value, err
}

// CloseTab is core.Core's CloseTab (request).
func (c *Client) CloseTab(name string) error {
	var r CloseTabResult
	return c.request("CloseTab", CloseTabParams{Name: name}, &r)
}

// EnterGlobal is core.Core's EnterGlobal (request).
func (c *Client) EnterGlobal(focused core.WorkspaceID) (core.WorkspaceView, error) {
	var r EnterGlobalResult
	err := c.request("EnterGlobal", EnterGlobalParams{Focused: focused}, &r)
	return r.Value, err
}

// Save is core.Core's Save (request).
func (c *Client) Save(id core.WorkspaceID) error {
	var r SaveResult
	return c.request("Save", SaveParams{ID: id}, &r)
}

// Registry is core.Core's Registry (local).
func (c *Client) Registry() core.RegistryView {
	var v0 core.RegistryView
	c.local(func(r *replica) { v0 = r.Registry() })
	return v0
}

// ReloadRegistry is core.Core's ReloadRegistry (request).
func (c *Client) ReloadRegistry() error {
	var r ReloadRegistryResult
	return c.request("ReloadRegistry", ReloadRegistryParams{}, &r)
}

// SaveSettings is core.Core's SaveSettings (request).
func (c *Client) SaveSettings(id core.WorkspaceID, settings config.Settings) error {
	var r SaveSettingsResult
	return c.request("SaveSettings", SaveSettingsParams{ID: id, Settings: settings}, &r)
}

// SetUIPrefs is core.Core's SetUIPrefs (request).
func (c *Client) SetUIPrefs(id core.WorkspaceID, prefs config.UIPrefs) error {
	var r SetUIPrefsResult
	return c.request("SetUIPrefs", SetUIPrefsParams{ID: id, Prefs: prefs}, &r)
}

// SetHelpScreensSeen is core.Core's SetHelpScreensSeen (request).
func (c *Client) SetHelpScreensSeen(id core.WorkspaceID, seen uint32) error {
	var r SetHelpScreensSeenResult
	return c.request("SetHelpScreensSeen", SetHelpScreensSeenParams{ID: id, Seen: seen}, &r)
}

// Views is core.Core's Views (local).
func (c *Client) Views(id core.WorkspaceID) []core.InstanceView {
	var v0 []core.InstanceView
	c.local(func(r *replica) { v0 = r.Views(id) })
	return v0
}

// View is core.Core's View (local).
func (c *Client) View(id core.InstanceID) (core.InstanceView, bool) {
	var v0 core.InstanceView
	var v1 bool
	c.local(func(r *replica) { v0, v1 = r.View(id) })
	return v0, v1
}

// Create is core.Core's Create (request).
func (c *Client) Create(id core.WorkspaceID, spec core.NewInstance, req core.ReqID) {
	var r CreateResult
	c.requestNoErr("Create", CreateParams{ID: id, Spec: spec, Req: req}, &r)
}

// Kill is core.Core's Kill (request).
func (c *Client) Kill(id core.InstanceID, req core.ReqID) {
	var r KillResult
	c.requestNoErr("Kill", KillParams{ID: id, Req: req}, &r)
}

// Pause is core.Core's Pause (request).
func (c *Client) Pause(id core.InstanceID, req core.ReqID) {
	var r PauseResult
	c.requestNoErr("Pause", PauseParams{ID: id, Req: req}, &r)
}

// Resume is core.Core's Resume (request).
func (c *Client) Resume(id core.InstanceID, req core.ReqID) {
	var r ResumeResult
	c.requestNoErr("Resume", ResumeParams{ID: id, Req: req}, &r)
}

// ResumeWith is core.Core's ResumeWith (request).
func (c *Client) ResumeWith(id core.InstanceID, opts launch.Options, base string, req core.ReqID) {
	var r ResumeWithResult
	c.requestNoErr("ResumeWith", ResumeWithParams{ID: id, Opts: opts, Base: base, Req: req}, &r)
}

// Recover is core.Core's Recover (request).
func (c *Client) Recover(id core.InstanceID, req core.ReqID) {
	var r RecoverResult
	c.requestNoErr("Recover", RecoverParams{ID: id, Req: req}, &r)
}

// Merge is core.Core's Merge (request).
func (c *Client) Merge(target core.InstanceID, source core.InstanceID, req core.ReqID) {
	var r MergeResult
	c.requestNoErr("Merge", MergeParams{Target: target, Source: source, Req: req}, &r)
}

// Push is core.Core's Push (request).
func (c *Client) Push(id core.InstanceID, req core.ReqID) {
	var r PushResult
	c.requestNoErr("Push", PushParams{ID: id, Req: req}, &r)
}

// SendPrompt is core.Core's SendPrompt (request).
func (c *Client) SendPrompt(id core.InstanceID, text string, req core.ReqID) {
	var r SendPromptResult
	c.requestNoErr("SendPrompt", SendPromptParams{ID: id, Text: text, Req: req}, &r)
}

// FetchIssue is core.Core's FetchIssue (request).
func (c *Client) FetchIssue(repo string, number int, req core.ReqID) {
	var r FetchIssueResult
	c.requestNoErr("FetchIssue", FetchIssueParams{Repo: repo, Number: number, Req: req}, &r)
}

// SetSelected is core.Core's SetSelected (cast).
func (c *Client) SetSelected(id core.InstanceID) {
	c.cast("SetSelected", SetSelectedParams{ID: id})
}

// MarkOutput is core.Core's MarkOutput (cast).
func (c *Client) MarkOutput(sessionName string) {
	c.cast("MarkOutput", MarkOutputParams{SessionName: sessionName})
}

// PaneOutput is core.Core's PaneOutput (cast).
func (c *Client) PaneOutput(id core.InstanceID) {
	c.cast("PaneOutput", PaneOutputParams{ID: id})
}

// PaneQuiet is core.Core's PaneQuiet (cast).
func (c *Client) PaneQuiet(id core.InstanceID) {
	c.cast("PaneQuiet", PaneQuietParams{ID: id})
}

// VerifyDead is core.Core's VerifyDead (cast).
func (c *Client) VerifyDead(id core.InstanceID) {
	c.cast("VerifyDead", VerifyDeadParams{ID: id})
}

// Program is core.Core's Program (local).
func (c *Client) Program() string {
	var v0 string
	c.local(func(r *replica) { v0 = r.Program() })
	return v0
}

// SetProgram is core.Core's SetProgram (request).
func (c *Client) SetProgram(program string) {
	var r SetProgramResult
	c.requestNoErr("SetProgram", SetProgramParams{Program: program}, &r)
}

// RCAuth is core.Core's RCAuth (local).
func (c *Client) RCAuth() session.RemoteControlAuth {
	var v0 session.RemoteControlAuth
	c.local(func(r *replica) { v0 = r.RCAuth() })
	return v0
}

// GitHubSnapshot is core.Core's GitHubSnapshot (local).
func (c *Client) GitHubSnapshot(repo string) (github.Snapshot, bool) {
	var v0 github.Snapshot
	var v1 bool
	c.local(func(r *replica) { v0, v1 = r.GitHubSnapshot(repo) })
	return v0, v1
}

// GitHubErr is core.Core's GitHubErr (local).
func (c *Client) GitHubErr(repo string) error {
	var err error
	c.local(func(r *replica) { err = r.GitHubErr(repo) })
	return err
}

// GitHubUnavailable is core.Core's GitHubUnavailable (local).
func (c *Client) GitHubUnavailable() bool {
	var v0 bool
	c.local(func(r *replica) { v0 = r.GitHubUnavailable() })
	return v0
}

// GitHubUnavailableReason is core.Core's GitHubUnavailableReason (local).
func (c *Client) GitHubUnavailableReason() string {
	var v0 string
	c.local(func(r *replica) { v0 = r.GitHubUnavailableReason() })
	return v0
}

// ExpediteGitHub is core.Core's ExpediteGitHub (cast).
func (c *Client) ExpediteGitHub() {
	c.cast("ExpediteGitHub", ExpediteGitHubParams{})
}

// AccountNames is core.Core's AccountNames (local).
func (c *Client) AccountNames() core.AccountNames {
	var v0 core.AccountNames
	c.local(func(r *replica) { v0 = r.AccountNames() })
	return v0
}

// AccountsLoaded is core.Core's AccountsLoaded (local).
func (c *Client) AccountsLoaded() bool {
	var v0 bool
	c.local(func(r *replica) { v0 = r.AccountsLoaded() })
	return v0
}

// HasExtraAccounts is core.Core's HasExtraAccounts (local).
func (c *Client) HasExtraAccounts() bool {
	var v0 bool
	c.local(func(r *replica) { v0 = r.HasExtraAccounts() })
	return v0
}

// Account is core.Core's Account (local).
func (c *Client) Account(name string) (account.Account, bool) {
	var v0 account.Account
	var v1 bool
	c.local(func(r *replica) { v0, v1 = r.Account(name) })
	return v0, v1
}

// RCAuthFor is core.Core's RCAuthFor (local).
func (c *Client) RCAuthFor(acct string) session.RemoteControlAuth {
	var v0 session.RemoteControlAuth
	c.local(func(r *replica) { v0 = r.RCAuthFor(acct) })
	return v0
}

// AccountLoggedOut is core.Core's AccountLoggedOut (local).
func (c *Client) AccountLoggedOut(acct string) bool {
	var v0 bool
	c.local(func(r *replica) { v0 = r.AccountLoggedOut(acct) })
	return v0
}

// AccountSync is core.Core's AccountSync (local).
func (c *Client) AccountSync(name string) (account.SyncReport, bool) {
	var v0 account.SyncReport
	var v1 bool
	c.local(func(r *replica) { v0, v1 = r.AccountSync(name) })
	return v0, v1
}

// AccountUsage is core.Core's AccountUsage (local).
func (c *Client) AccountUsage(name string) (account.Usage, error) {
	var v0 account.Usage
	var err error
	c.local(func(r *replica) { v0, err = r.AccountUsage(name) })
	return v0, err
}

// AccountEnv is core.Core's AccountEnv (local).
func (c *Client) AccountEnv(name string) ([]string, error) {
	var v0 []string
	var err error
	c.local(func(r *replica) { v0, err = r.AccountEnv(name) })
	return v0, err
}

// ClaudeProgram is core.Core's ClaudeProgram (local).
func (c *Client) ClaudeProgram() string {
	var v0 string
	c.local(func(r *replica) { v0 = r.ClaudeProgram() })
	return v0
}

// ReloadAccounts is core.Core's ReloadAccounts (request).
func (c *Client) ReloadAccounts() {
	var r ReloadAccountsResult
	c.requestNoErr("ReloadAccounts", ReloadAccountsParams{}, &r)
}

// RequestAccountsRefresh is core.Core's RequestAccountsRefresh (cast).
func (c *Client) RequestAccountsRefresh(withDefault bool) {
	c.cast("RequestAccountsRefresh", RequestAccountsRefreshParams{WithDefault: withDefault})
}

// RequestUsageProbe is core.Core's RequestUsageProbe (cast).
func (c *Client) RequestUsageProbe() {
	c.cast("RequestUsageProbe", RequestUsageProbeParams{})
}

// AddAccount is core.Core's AddAccount (request).
func (c *Client) AddAccount(name string) (string, error) {
	var r AddAccountResult
	err := c.request("AddAccount", AddAccountParams{Name: name}, &r)
	return r.Value, err
}

// RemoveAccount is core.Core's RemoveAccount (request).
func (c *Client) RemoveAccount(name string) error {
	var r RemoveAccountResult
	return c.request("RemoveAccount", RemoveAccountParams{Name: name}, &r)
}

// SetDefaultAccount is core.Core's SetDefaultAccount (request).
func (c *Client) SetDefaultAccount(name string) error {
	var r SetDefaultAccountResult
	return c.request("SetDefaultAccount", SetDefaultAccountParams{Name: name}, &r)
}
