package rpc

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"reflect"
	"testing"
	"time"

	"github.com/aidan-bailey/loom/core"
	"github.com/aidan-bailey/loom/session"
	"github.com/aidan-bailey/loom/session/git"
	"github.com/aidan-bailey/loom/session/github"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var update = flag.Bool("update", false, "rewrite docs/specs/protocol.md")

// TestEvents_RoundTrip: every event survives its frame, the ones holding
// errors with their text and sentinels.
func TestEvents_RoundTrip(t *testing.T) {
	samples := core.EventTypes()
	samples = append(samples,
		core.Notice{Err: core.ErrNoSession},
		core.Reply{Req: 2, ID: 3, Err: errors.New("kill x: worktree locked")},
		core.ViewsChanged{WS: 1, Views: []core.InstanceView{{
			ID: 4, Title: "x", Status: session.Running, StatusSince: time.Unix(100, 0),
			Diff: git.DiffStats{Added: 1, Error: errors.New("no base")}, HasDiff: true,
		}}},
		core.GitHubChanged{View: core.GitHubView{
			Snapshots: map[string]github.Snapshot{"/r": {Issues: map[int]github.Issue{7: {Number: 7}}}},
			Errs:      map[string]string{"/s": "no remote"},
		}},
	)
	for _, ev := range samples {
		f, err := encodeEvent(ev)
		require.NoError(t, err)
		line, err := json.Marshal(f)
		require.NoError(t, err)
		var back Frame
		require.NoError(t, json.Unmarshal(line, &back))
		got, err := decodeEvent(back)
		require.NoError(t, err)
		assert.Equal(t, fmt.Sprintf("%+v", ev), fmt.Sprintf("%+v", got), "%T", ev)
	}
	got, err := decodeEvent(mustFrame(t, core.Notice{Err: core.ErrNoSession}))
	require.NoError(t, err)
	assert.True(t, errors.Is(got.(core.Notice).Err, core.ErrNoSession), "a sentinel survives the wire")
}

func mustFrame(t *testing.T, ev core.Event) Frame {
	f, err := encodeEvent(ev)
	require.NoError(t, err)
	return f
}

// TestProtocolReference keeps docs/specs/protocol.md, the wire's reference,
// in step with the code: every method's kind, parameters and result, and
// every event, as their frames encode zero values. Run with -update to
// rewrite it after a change (and bump Protocol if the change is
// incompatible).
func TestProtocolReference(t *testing.T) {
	var b bytes.Buffer
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }
	p("# Loom wire protocol, version %d\n\n", Protocol)
	p("Generated by `go test ./core/rpc -run TestProtocolReference -update`; do not edit.\n\n")
	p("Newline-delimited JSON frames (`core/rpc.Frame`). Each side's first frame is a hello\n")
	p("(`{\"hello\":{\"protocol\":%d,\"build\":\"…\"}}`). A request is `{\"id\":N,\"method\":M,\"params\":{…}}`;\n", Protocol)
	p("its reply `{\"id\":N,\"result\":{…},\"error\":{\"code\":…,\"message\":…}}` follows the events the\n")
	p("request produced. A cast has no id and no reply. An event is `{\"event\":Name,\"data\":{…}}`.\n")
	p("`{\"fatal\":{…}}` says the model panicked; every later call fails with it. A client is sent\n")
	p("the whole published state when it connects, then every change.\n\n")
	p("Kinds: **request** (a reply follows), **cast** (one way), **local** (a client answers it from its\n")
	p("replica of the published state; the server answers it as a request too).\n\n")

	p("## Barrier\n\n")
	p("`%s` is a request that is no Core method: the server publishes what the model produced, then\n", pingMethod)
	p("replies `{}`, so every frame the server wrote before the reply has been read when it arrives.\n")
	p("`%s`\n\n", compact(t, Frame{ID: 1, Method: pingMethod, Params: json.RawMessage("{}")}))

	p("## Request IDs\n\n")
	p("A client numbers the requests that want a `Reply` itself (the `req` params, `core.ReqID`), from 1 and below\n")
	p("2^32; 0 asks for no Reply. A server serves several clients, so it hands the model each request ID with the\n")
	p("connection's number in its high 32 bits, and the events naming a request come back to its client with the\n")
	p("client's own ID: a `Reply`, and the `Notice` of a request's job, go to that client alone; `Started` and\n")
	p("`Recovered` go to every client, naming the request (`Req`) only to the one that made it.\n\n")

	p("## Refused hello\n\n")
	p("A server answers a hello of another protocol with an error frame that has no id, then closes:\n")
	p("`%s`\n\n", compact(t, Frame{Error: mismatchError()}))

	var stateEvents []string
	for _, ev := range core.EventTypes() {
		if coalesceKey(ev) != "" {
			stateEvents = append(stateEvents, reflect.TypeOf(ev).Name())
		}
	}
	order := []core.Event{core.WorkspacesChanged{}, core.ModelChanged{}, core.AccountsChanged{}, core.GitHubChanged{}, core.ViewsChanged{}}
	require.Len(t, order, len(stateEvents), "a state event was added: say where it goes in the order below")
	p("## State events\n\n")
	p("The events that make up the published state, which a client's replica keeps, in the order the model\n")
	p("publishes them and a client's Sync hands them out, newest state only and ahead of the other events:\n\n")
	for _, ev := range order {
		require.NotEmpty(t, coalesceKey(ev), "%T is a state event", ev)
		name := reflect.TypeOf(ev).Name()
		if name == "ViewsChanged" {
			name += " (one per workspace, by its `WS`)"
		}
		p("- %s\n", name)
	}
	p("\nA server queues at most one of each (one per workspace for `ViewsChanged`) for a connection: a newer\n")
	p("one replaces an older one still queued, in its place. Replies and the other events keep their order.\n\n")

	p("## Errors\n\n")
	p("An error crosses as `{\"code\":C,\"message\":M}` (`core.WireError`). The code keeps the identity a receiver\n")
	p("tests with errors.Is, and every other error arrives as its message: `%s`, `%s`, `%s`, `%s`\n",
		core.CodeNotFound, core.CodeRefused, core.CodeStorage, core.CodeError)
	p("(a failure that is none of the others), `%s` (the model panicked), `%s` (a frame the other side could\n", core.CodePanic, core.CodeProtocol)
	p("not use; fatal to a client), `%s` (the peer does not know the method; an ordinary error, so a newer client\n", core.CodeUnsupported)
	p("can probe an older server) and `%s` (a refused hello). Examples, a `Notice` and a `Reply` carrying one:\n\n", core.CodeMismatch)
	p("`%s`\n\n", compact(t, mustFrame(t, core.Notice{Err: core.ErrNoSession})))
	p("`%s`\n\n", compact(t, mustFrame(t, core.Reply{Req: 2, ID: 3, Err: errors.New("kill x: worktree locked")})))

	p("## Methods\n\n")
	for _, m := range methods {
		p("### %s (%s)\n\nParams: `%s`\n\nResult: `%s`\n\n", m.Name, m.Kind, compact(t, m.Params), compact(t, m.Result))
	}
	p("## Events\n\n")
	for _, ev := range core.EventTypes() {
		p("### %s\n\n`%s`\n\n", reflect.TypeOf(ev).Name(), compact(t, ev))
	}
	const path = "../../docs/specs/protocol.md"
	if *update {
		require.NoError(t, os.WriteFile(path, b.Bytes(), 0o644))
	}
	want, err := os.ReadFile(path)
	require.NoError(t, err, "run with -update to write it")
	assert.Equal(t, string(want), b.String(), "the protocol changed: run with -update, and bump Protocol if it is incompatible")
}

func compact(t *testing.T, v any) string {
	data, err := json.Marshal(v)
	require.NoError(t, err)
	return string(data)
}

var (
	timeType  = reflect.TypeOf(time.Time{})
	errorType = reflect.TypeOf((*error)(nil)).Elem()
)

// normalize deep-copies v for comparing a value that crossed the wire with
// one that did not: every time.Time becomes the same instant in UTC without
// its monotonic reading (the wire keeps the instant, nothing more), and
// every error value an error with the same text (the wire keeps the text).
// Nothing else changes, so a field the wire drops, or a nil that comes back
// empty, still shows.
func normalize(v any) any {
	if v == nil {
		return nil
	}
	return normalizeValue(reflect.ValueOf(v)).Interface()
}

func normalizeValue(v reflect.Value) reflect.Value {
	t := v.Type()
	out := reflect.New(t).Elem()
	switch {
	case t == timeType:
		out.Set(reflect.ValueOf(v.Interface().(time.Time).Round(0).UTC()))
		return out
	}
	switch t.Kind() {
	case reflect.Interface:
		if v.IsNil() {
			return out
		}
		if err, ok := v.Interface().(error); ok {
			if e := reflect.ValueOf(errors.New(err.Error())); e.Type().AssignableTo(t) {
				out.Set(e)
				return out
			}
		}
		out.Set(normalizeValue(v.Elem()))
	case reflect.Ptr:
		if v.IsNil() {
			return out
		}
		p := reflect.New(t.Elem())
		p.Elem().Set(normalizeValue(v.Elem()))
		out.Set(p)
	case reflect.Slice:
		if v.IsNil() {
			return out
		}
		s := reflect.MakeSlice(t, v.Len(), v.Len())
		for i := 0; i < v.Len(); i++ {
			s.Index(i).Set(normalizeValue(v.Index(i)))
		}
		out.Set(s)
	case reflect.Array:
		for i := 0; i < v.Len(); i++ {
			out.Index(i).Set(normalizeValue(v.Index(i)))
		}
	case reflect.Map:
		if v.IsNil() {
			return out
		}
		m := reflect.MakeMapWithSize(t, v.Len())
		for it := v.MapRange(); it.Next(); {
			m.SetMapIndex(normalizeValue(it.Key()), normalizeValue(it.Value()))
		}
		out.Set(m)
	case reflect.Struct:
		out.Set(v) // what normalize cannot reach, the unexported fields, is copied as it is
		for i := 0; i < t.NumField(); i++ {
			if f := out.Field(i); f.CanSet() {
				f.Set(normalizeValue(v.Field(i)))
			}
		}
	default:
		out.Set(v)
	}
	return out
}

// fill sets every exported field of v, however deep, to a value that is not
// the zero one: a string "x", a number 1, true, one element in each slice
// and map, an allocated pointer, a fixed time and an error "e".
func fill(t *testing.T, v reflect.Value, path string, depth int) {
	t.Helper()
	if depth > 12 {
		return // a type that nests itself: a zero below here is not the codec's doing
	}
	typ := v.Type()
	switch {
	case typ == timeType:
		v.Set(reflect.ValueOf(time.Unix(1e9, 0)))
		return
	case typ == errorType:
		v.Set(reflect.ValueOf(errors.New("e")))
		return
	}
	switch typ.Kind() {
	case reflect.String:
		v.SetString("x")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Ptr:
		v.Set(reflect.New(typ.Elem()))
		fill(t, v.Elem(), path, depth+1)
	case reflect.Slice:
		s := reflect.MakeSlice(typ, 1, 1)
		fill(t, s.Index(0), path+"[]", depth+1)
		v.Set(s)
	case reflect.Map:
		k := reflect.New(typ.Key()).Elem()
		fill(t, k, path+"{key}", depth+1)
		e := reflect.New(typ.Elem()).Elem()
		fill(t, e, path+"{}", depth+1)
		m := reflect.MakeMap(typ)
		m.SetMapIndex(k, e)
		v.Set(m)
	case reflect.Struct:
		for i := 0; i < typ.NumField(); i++ {
			if typ.Field(i).IsExported() {
				fill(t, v.Field(i), path+"."+typ.Field(i).Name, depth+1)
			}
		}
	default:
		t.Fatalf("%s: fill cannot set a %s (%s): teach it, or the type does not belong on the wire", path, typ.Kind(), typ)
	}
}

// filled is a value of typ with every field set (fill).
func filled(t *testing.T, typ reflect.Type) reflect.Value {
	t.Helper()
	v := reflect.New(typ).Elem()
	fill(t, v, typ.Name(), 0)
	return v
}

// TestWire_EveryFieldSurvives: every field of every event and of the views
// they carry comes back from the wire. A field a codec drops (a json:"-"
// tag, or a field added to a type whose JSON form is a struct of its own,
// as git.DiffStats') is a client that silently reads zero.
func TestWire_EveryFieldSurvives(t *testing.T) {
	for _, ev := range core.EventTypes() {
		typ := reflect.TypeOf(ev)
		t.Run(typ.Name(), func(t *testing.T) {
			full := filled(t, typ).Interface().(core.Event)
			f, err := encodeEvent(full)
			require.NoError(t, err)
			line, err := json.Marshal(f)
			require.NoError(t, err)
			var back Frame
			require.NoError(t, json.Unmarshal(line, &back))
			got, err := decodeEvent(back)
			require.NoError(t, err)
			assert.Equal(t, normalize(full), normalize(got))
		})
	}
	for _, v := range []any{core.InstanceView{}, core.WorkspaceView{}, core.AccountsView{}, core.GitHubView{}} {
		typ := reflect.TypeOf(v)
		t.Run(typ.Name(), func(t *testing.T) {
			full := filled(t, typ).Interface()
			data, err := json.Marshal(full)
			require.NoError(t, err)
			back := reflect.New(typ)
			require.NoError(t, json.Unmarshal(data, back.Interface()))
			assert.Equal(t, normalize(full), normalize(back.Elem().Interface()))
		})
	}
}
